# Generated by Django 5.2.7 on 2025-10-14 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(help_text='Unique 10 or 13 digit ISBN.', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be 10 or 13 digits.', regex='^(?=(?:\\D*\\d){10}(?:(?:\\D*\\d){3})?$)[\\d-]+$')])),
                ('cost_usd', models.DecimalField(decimal_places=2, help_text='Cost in USD, must be greater than 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated selling price in local currency.', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(help_text='Stock quantity, cannot be negative.')),
                ('category', models.CharField(max_length=100)),
                ('supplier_country', models.CharField(help_text='Two-letter country code of the supplier (e.g., ES).', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
